In [1]:
import numpy as np

In [11]:
arr1 = np.array(range(1, 10))
print("this is arr1\t", arr1)
print("this is arr1 no. of rows\t", arr1.ndim)
print("this is arr1 shape\t", arr1.shape)
print("this is arr1 size\t", arr1.size)
print("this is arr1 data type\t", arr1.dtype)

this is arr1	 [1 2 3 4 5 6 7 8 9]
this is arr1 no. of rows	 1
this is arr1 shape	 (9,)
this is arr1 size	 9
this is arr1 data type	 int32


In [13]:
arr2 = np.array([1,2,3])
print(arr2)
print(arr2.shape)

[1 2 3]
(3,)


In [17]:
arr3 = np.zeros((5,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
arr4 = np.ones((7,5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
arr5 = np.empty((5,8))
print(arr5)

[[2.21438343e-291 0.00000000e+000 4.27410459e-314 0.00000000e+000
  0.00000000e+000 2.05226840e-289 1.03621951e-305 4.66145799e-317]
 [1.30578349e-316 4.49909222e-301 1.21071940e-305 1.08009953e-305
  7.38272898e-308 8.03135246e-291 0.00000000e+000 8.91238233e-313]
 [0.00000000e+000 7.21739999e-308 1.68969595e-291 6.57818695e-312
  8.84872245e-312 2.21464031e-291 0.00000000e+000 2.12393294e-314]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.21543540e-291
  2.97275070e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [25]:
np.arange(1,10,3)

array([1, 4, 7])

In [26]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [32]:
arr6 = np.arange(1,10)
print(arr6)
arr6.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr7 = np.arange(20)
print(arr7)
print(arr7[4])
print(arr7[::-3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[19 16 13 10  7  4  1]


In [44]:
arr8 = np.diag((np.arange(1,23)))
print(arr8)
print(arr8[4])
print("\n")
print(arr8[2:10:3])

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [51]:
print(arr6, "\n")
print(arr6+1, "\n")
print(arr6 * 2, "\n")
print(arr6 ** 2, "\n")

[1 2 3 4 5 6 7 8 9] 

[ 2  3  4  5  6  7  8  9 10] 

[ 2  4  6  8 10 12 14 16 18] 

[ 1  4  9 16 25 36 49 64 81] 

